#!/bin/bash
#
#	/etc/rc.d/init.d/notion
#
# Start the Notion ResearchPACS.
#
# chkconfig: 2345 90 10
# description: Notion ResearchPACS

# processname: notion

source /etc/rc.d/init.d/functions

if [ -r /etc/notion.conf ];
then
  . /etc/notion.conf
else
  USER=qin
  NOTION_HOME=/research/images/Notion/Notion
  PACS_DIR=/research/images/Notion/
  JAVA_ARGS="$JAVA_ARGS -Xmx1048m -Xdebug -Xrunjdwp:transport=dt_socket,address=8050,server=y,suspend=n"
  JAVA_HOME=/usr/java/default
fi

RETVAL=0
prog="notion"
desc="Notion ResearchPACS"

export PATH=$PATH:/usr/local/sbin

start() {
  echo -n $"Starting $desc: "
  mkdir -p ${PACS_DIR}
  touch /var/log/$prog.error
  chown $USER /var/log/$prog.error ${PACS_DIR}

  daemonize -e /var/log/$prog.error -c $NOTION_HOME -p /var/run/$prog.pid -l /var/lock/subsys/$prog -u $USER $JAVA_HOME/bin/java $JAVA_ARGS -jar $NOTION_HOME/Notion.jar $PACS_DIR
  RETVAL=$?
  [ $RETVAL -eq 0 ] && success || failure
  echo
}

stop() {
  echo -n $"Shutting down $desc: "
  __pids_var_run "$prog" "$pid_file"
  RETVAL=$?
  # Exit if we're not running
  if [ $RETVAL -eq 3 ]; then
    failure "$prog is not running"
    echo
    return $RETVAL
  fi

  killproc -p /var/run/$prog.pid $prog
  RETVAL=$?
  [ $RETVAL -eq 0 ] && success || failure
  echo
  [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
  [ $RETVAL -eq 0 ] && rm -f /var/run/$prog.pid
  return $RETVAL
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status $prog -p /var/run/$prog.pid
    ;;
  restart)
    stop
    start
    RETVAL=$?
    ;;
  condrestart)
    [ -e /var/lock/subsys/$prog ] && restart
    RETVAL=$?
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|condrestart}"
    RETVAL=1
esac

exit $RETVAL
