

CREATE TABLE LOOKUP (
	LookupKey INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY ,
	PoolKey INT NOT NULL,
	Type VARCHAR(32),
	Name VARCHAR(250),
	Value VARCHAR(250)
);

CREATE INDEX Lookup_idx1 on LOOKUP ( PoolKey, Type );
CREATE INDEX Lookup_idx2 on LOOKUP ( PoolKey, Type, Name );


CREATE TABLE SCRIPT (
	ScriptKey INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	PoolKey INT NOT NULL,
	Tag VARCHAR(64),
	Script LONG VARCHAR
);

CREATE INDEX Script_idx1 on SCRIPT ( PoolKey, Tag );
CREATE INDEX Script_idx2 on SCRIPT ( PoolKey );